name: Memolingua-Admin-Workflow
run-name: ${{ github.actor }} is running GitHub Actions for Memolingua Admin
on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage
jobs:
  installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Agent initiation
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
      - name: copy build file
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/mem-admin/html
